/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'CLHACKNE' at '22/07/15 14:39' with Gradle 2.4
 *
 * @author CLHACKNE, @date 22/07/15 14:39
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
